name: spire_e_doctors
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  page_transition: ^2.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  flutter_login_facebook: ^1.6.2
  intl_phone_field: ^3.2.0
  flutter_carousel_widget: ^2.2.0
  google_sign_in: ^5.0.7
  dio: ^5.4.0
  animated_bottom_navigation_bar: ^1.3.2
  flutter_otp_text_field: ^1.1.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LatoMedium.ttf
          weight: 500
        - asset: assets/fonts/LatoSemiBold.ttf
          weight: 600
    - family: League Spartan
      fonts: 
        - asset: assets/fonts/LeagueSpartanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LeagueSpartanMedium.ttf
          weight: 500

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900

    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Medium.ttf
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 900
        - asset: assets/fonts/Barlow-Italic.ttf
          style: italic

